### PR TITLE
Fixes awaits

### LINKED ISSUE #14: [PROPOSAL] Make void functions return Future
There are some functions, mainly in `SessionController` where it returns void but is actually async, which means the client won't wait for operations. In the `AgoraClient`'s `_initAgoraRtcEngine()` it doesn't catches errors because of this.

### PR DESCRIPTION
**Pull request by Ascenio**
Fix/awaits for futures

Closes #14.

I've added the [unawaited_futures](https://dart-lang.github.io/linter/lints/unawaited_futures.html) to avoid regressions, but let me know if you disagree with it.

## Release Notes

- Fixes futures not being returned

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] The GitHub Actions pass building and linting. Linter returns no warnings or errors.
- [X] The QA checklist below has been completed

## Pull request type

Please check the type of change your PR introduces:
- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

It doesn't return Futures and so doesn't await for them.

Issue Number: #14 

## What is the new behavior?

Now it returns Futures when needed but also awaits for them.

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

### UIKit Update Checklist (Minor or Patch Release)

- [X] Using the latest version of Agora's Video SDK
- [X] Example apps are all functional
- [X] Core features are still working (both ways across platforms)
	- [ ] Camera + Mic muting works for local and remote users
	- [ ] Users are added and removed correctly when they join and leave the channel
	- [ ] Older versions of the library gracefully handle changes (Create issue if not)
	- [ ] Builtin buttons all work as expected
- [ ] Any newly deprecated methods are flagged as such inline and in documentation

### UIKit Update Checklist (Major Release)

- [X] The above checklist is completed (except backwards compatibility)
- [ ] Thoroughly tested for crashes, across multiple platforms at the same time

### CODE REVIEW

**Review by tadaspetra — APPROVED** [review]
Looks good to me!

**Comment by Ascenio** [comment]
Oh sorry, I didn't noticed there was a dev branch.

**Comment by tadaspetra** [comment]
> Oh sorry, I didn't noticed there was a dev branch.

No worries, we didn't realize either. We have a meeting planned after this weekend to go through all the PR's and set up the GitHub even nicer. 

As a side note, these are really great PR's and we really appreciate them 😊

**Comment by Ascenio** [comment]
I'm glad I could help. It's always nice to contribute to open source :smile:

**Pull request merged**
