### PR TITLE
moving to v0.0.3

### PR DESCRIPTION
**Pull request by Meherdeep**

### CODE REVIEW

**Comment by maxxfrazer** [comment]
@Meherdeep could you add an image to the README for this release?

**Comment by Meherdeep** [comment]
@maxxfrazer Yes, I will do that right now.

**Comment by Meherdeep** [comment]
@maxxfrazer I have added the image 🤙

**Review by maxxfrazer — APPROVED** [review]
LGTM, let's see about `dev -> main`

**Pull request merged**
